FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Optional: install nodemon globally
RUN npm install -g nodemon

EXPOSE 5000

CMD ["npm", "run", "start:dev", "--", "--host"]

